# Generated by Django 6.0.3 on 2026-03-09 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='position',
            name='election_id',
        ),
        migrations.AddField(
            model_name='candidate',
            name='manifesto',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='position',
            name='order',
            field=models.IntegerField(default=0, help_text='Display order on the ballot'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='photo',
            field=models.ImageField(default='', upload_to='candidates/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='position',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
