# Generated by Django 5.2.8 on 2026-03-15 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_candidate_bio_remove_position_election_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='University General Election 2026', max_length=200)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('results_certified', models.BooleanField(default=False)),
                ('certified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Election Configuration',
                'verbose_name_plural': 'Election Configuration',
            },
        ),
    ]
