# Generated by Django 5.2.8 on 2026-03-27 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_electionconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
