"""
Django settings for udes project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
import os
import environ
import dj_database_url
from pathlib import Path

# This points to the folder where manage.py lives
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(
    DEBUG=(bool, False)
)

# Explicitly tell it where the .env file is
ENV_FILE = os.path.join(BASE_DIR, '.env')

if os.path.exists(ENV_FILE):
    environ.Env.read_env(ENV_FILE)
else:
    print("WARNING: .env file not found at", ENV_FILE)

# ... further down in the DATABASES section ...

# settings.py

# Pull the URL from .env and immediately strip any hidden spaces
# Extract the URL from .env, but use .strip() to kill any hidden spaces
DATABASE_URL_RAW = env('DATABASE_URL', default='')
DATABASE_URL_CLEAN = DATABASE_URL_RAW.strip()

DATABASES = {
    'default': dj_database_url.parse(
        DATABASE_URL_CLEAN,
        conn_max_age=600,
        ssl_require=True
    )
}

# Add this line temporarily to see exactly what Python sees in the console
print(f"--- DATABASE URL LOADED: '{DATABASE_URL_CLEAN}' ---")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/



# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = ['*']

# Application definition

# udes/settings.py

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third Party
    'rest_framework',
    
    # Local Apps
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
    # ADD THIS LINE HERE:
    'core.middleware.KioskSecurityMiddleware', 
]

ROOT_URLCONF = 'udes.urls'

import os

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'udes.wsgi.application'

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# settings.py
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'udes_db',           # Ensure you created this in pgAdmin!
#         'USER': 'postgres',
#         'PASSWORD': 'Grandpiano2003', # Use the exact password from Step 2
#         'HOST': '127.0.0.1',
#         'PORT': '5432',
#     }
# }

#render postgresql database




# Password validation # https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'

# 1. ADD THIS LINE: This is where Django will "collect" files for production
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# 2. Tell Django where to find your development static files
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

import os

# The URL used to access the media through the browser
MEDIA_URL = '/media/'

# The actual directory on your computer where files are saved
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# Authentication Redirects
# udes/settings.py
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'root_redirect'

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC' # You can change this to 'Africa/Monrovia' if you want local time
USE_I18N = True
USE_TZ = True

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'